### ISSUE TITLE
Project Status?

### ISSUE THREAD

**Issue by shoreliner** [Hoektronics/BotQueue#158]
Hi There;

David from PrintM3D here.  We run a rather large print farm for many of our in-house machines.  However, we've never went the way of a true optimization system... while botqueue has always in the back of my mind since hearing about it many years ago, I never had the time to actually try it out.

Are localized installations possbile?  I visited the site, but I can't seem to determine if the project is still active.  I'd love to contribute. =)

**Comment by Jnesselr** [comment]
Localized instances are definitely possible, or at least were the last time I attempted one.

The project is in a bit of a limbo status. I'm working on version 2 of the software which is pretty much a complete rewrite (and hence time consuming). I've found out recently version 1 is broken due to some dependencies changing out from under me.

If you'd like to contribute, one way I would be super appreciative of is helping diagnose the issues with the current version and running experiments so I can at least put the current version back into a stable and working state (and maybe improve my documentation a bit since that's something I want to focus on for v2 anyway.

Please shoot me an email at admin [at] [my username] [dot] org if you'd like to help with that and we can discuss switching to something like hangouts, telegram, etc.
